### ISSUE TITLE
Update the library to fully support Processing IDE 3.0

### ISSUE THREAD

**Issue by Avamander** [extrapixel/gif-animation#9]

**Comment by extrapixel** [comment]
@Avamander do you have time to have a look into that?

**Comment by Avamander** [comment]
I am currently testing the library. Will post the results. The one thing I encountered was that the built in IDE's library manager fails to update downloaded 2.3 to 2.3.1, also when I tried to install the library through the manager at the beginning it did not let me, it told me it was installed but it actually wasn't. So something is not exactly right.

**Comment by Avamander** [comment]
Yeah, the sketch that worked with IDE 2.x (that used this library) does not work any more.

    anim = new Gif(this, "anim.gif");

Results in: "NoSuchMethodError: You may be using a library that's incompatible with this version of Processing"

**Comment by extrapixel** [comment]
Yes I think there is this updating issue, too #3 . I'm sure both are easy fixes. Does someone have the spare time to have a look at it? @aib , @jimcavoli , @nate-opti ?

**Comment by jimcavoli** [comment]
A little busy for the next few weeks, but I may find a minute this weekend with Labor Day if all goes well. I'll let you know if I can do anything.

**Comment by extrapixel** [comment]
Work has been done by @01010101 : https://github.com/01010101/GifAnimation
Back-porting here is in progress

**Comment by jpw1116** [comment]
We're getting a 404 for the [inline download link](https://github.com/extrapixel/gif-animation/tree/3.0#download)—it's pointing to https://github.com/01010101/GifAnimation/tree/master/download/GifAnimation.zip

Is the correct one https://github.com/01010101/GifAnimation/archive/master.zip . . . because installing that in my .../Processing-3.2/lib destination does not allow Processing's menu to add the library (the dialog claims GifAnimation 2.3.1 is not compatible).
